CREATE DATABASE IF NOT EXISTS erms CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE erms;

CREATE TABLE IF NOT EXISTS users (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    employee_id VARCHAR(50) NOT NULL,
    full_name VARCHAR(120) NOT NULL,
    role ENUM('admin', 'employee') NOT NULL DEFAULT 'employee',
    password_hash VARCHAR(255) NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_users_employee_id (employee_id)
) ENGINE=InnoDB;
